name: deploy blog

on:
  push:
    branches:
      - master # default branch

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build and Deploy
        run: |
          yarn install 
          yarn build
      - name: Deploy
        uses: easingthemes/ssh-deploy@main
        env:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            ARGS: "-rlgoDzvc -i"
            REMOTE_USER: ${{ secrets.BLOGUSER }}
            REMOTE_HOST: ${{ secrets.BLOGIP }}
            SOURCE: ./public/
            TARGET: /data/monto-blog/public/